import React, { createContext, useContext, useState } from 'react';
import { dataTranslationsPT, dataTranslationsEN, dataTranslationsES } from './dataTranslations';

type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    ...dataTranslationsPT,
    // Navigation
    'nav.home': 'Início',
    'nav.markets': 'Mercados',
    'nav.vendors': 'Vendedores',
    'nav.itineraries': 'Roteiros',
    'nav.reviews': 'Avaliações',
    
    // Hero
    'hero.title': 'Descubra os Mercados Públicos do Recife',
    'hero.subtitle': 'Sabores autênticos, artesanato único e a verdadeira cultura pernambucana te esperam',
    'hero.cta': 'Explorar Mercados',
    
    // Common
    'common.location': 'Localização',
    'common.hours': 'Horário',
    'common.highlights': 'Destaques',
    'common.viewDetails': 'Ver Detalhes',
    'common.search': 'Buscar',
    'common.searchVendors': 'Buscar por nome, especialidade ou mercado',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.reviews': 'Avaliações',
    'common.photos': 'Fotos',
    'common.cancel': 'Cancelar',
    
    // Markets
    'markets.title': 'Principais Mercados',
    'markets.subtitle': 'Conheça os mercados mais tradicionais e vibrantes do Recife',
    'markets.saoJose.name': 'Mercado de São José',
    'markets.saoJose.desc': 'O mais antigo mercado público do Brasil em funcionamento contínuo, fundado em 1875.',
    'markets.boaVista.name': 'Mercado da Boa Vista',
    'markets.boaVista.desc': 'Conhecido pela variedade de produtos frescos e pela autenticidade.',
    'markets.casaAmarela.name': 'Mercado de Casa Amarela',
    'markets.casaAmarela.desc': 'Um mercado vibrante e acolhedor, onde você encontra desde produtos alimentícios até artesanato.',
    
    // Market Details
    'market.about': 'Sobre o Mercado',
    'market.history': 'História',
    'market.products': 'Produtos',
    'market.howToGet': 'Como Chegar',
    'market.gallery': 'Galeria',
    'market.featuredVendors': 'Vendedores em Destaque',
    
    // Vendors
    'vendors.title': 'Conheça os Vendedores',
    'vendors.subtitle': 'As pessoas que fazem a magia acontecer nos mercados',
    'vendors.filterByProduct': 'Filtrar por Produto',
    'vendors.location': 'Localização na banca',
    'vendors.specialty': 'Especialidade',
    'vendors.tabList': 'Vendedores',
    'vendors.tabRegister': 'Cadastre-se como Vendedor',
    'vendors.registerTitle': 'Cadastre-se como Vendedor',
    'vendors.registerSubtitle': 'Compartilhe sua história e produtos com os visitantes',
    'vendors.formName': 'Nome',
    'vendors.formNamePlaceholder': 'Seu nome ou nome da banca',
    'vendors.formDescription': 'Descrição / História',
    'vendors.formDescriptionPlaceholder': 'Conte sua história, como começou, tradições familiares...',
    'vendors.formSpecialty': 'Especialidade',
    'vendors.formSpecialtyPlaceholder': 'Ex: Ervas medicinais e chás naturais',
    'vendors.formMarket': 'Mercado onde atua',
    'vendors.formMarketPlaceholder': 'Selecione o mercado',
    'vendors.formProducts': 'Produtos que vende',
    'vendors.formLocation': 'Localização da Banca',
    'vendors.formLocationPlaceholder': 'Ex: Banca 12, Corredor A',
    'vendors.productErvas': 'Ervas',
    'vendors.productEspeciarias': 'Especiarias',
    'vendors.productArtesanato': 'Artesanato',
    'vendors.productComida': 'Comida',
    'vendors.productFrutas': 'Frutas',
    'vendors.productCeramica': 'Cerâmica',
    'vendors.productChas': 'Chás',
    'vendors.productTapioca': 'Tapioca',
    'vendors.formBadges': 'Selos de Autenticidade',
    'vendors.formBadgesDescription': 'Destaque suas características especiais',
    'vendors.badgeHandmade': '🎨 Feito à Mão',
    'vendors.badgeLocal': '📍 Produção Local',
    'vendors.badgeFamily': '👨‍👩‍👧‍👦 Receita de Família',
    'vendors.submitButton': 'Cadastrar',
    'vendors.submitting': 'Cadastrando...',
    'vendors.updateButton': 'Atualizar',
    'vendors.updating': 'Atualizando...',
    'vendors.successMessage': 'Cadastro realizado com sucesso!',
    'vendors.errorMessage': 'Erro ao cadastrar. Tente novamente.',
    'vendors.loginRequired': 'Você precisa estar logado para se cadastrar como vendedor',
    'vendors.editProfile': 'Editar Perfil',
    'vendors.deleteProfile': 'Apagar Perfil',
    'vendors.deleteConfirm': 'Tem certeza que deseja apagar seu perfil? Esta ação não pode ser desfeita.',
    'vendors.deleteSuccess': 'Perfil apagado com sucesso!',
    'vendors.deleteError': 'Erro ao apagar perfil. Tente novamente.',
    'vendors.tabEdit': 'Editar Perfil',
    'vendors.noVendors': 'Nenhum vendedor cadastrado ainda.',
    
    // Itineraries
    'itineraries.title': 'Roteiros Sugeridos',
    'itineraries.subtitle': 'Planeje sua visita com nossos guias temáticos',
    'itineraries.duration': 'Duração',
    'itineraries.stops': 'Paradas',
    'itineraries.checklist': 'Lista de Experiências',
    
    // Reviews
    'reviews.title': 'O Que Dizem os Visitantes',
    'reviews.subtitle': 'Experiências reais de quem já visitou',
    'reviews.leaveReview': 'Deixar Avaliação',
    'reviews.userGallery': 'Galeria de Visitantes',
    'reviews.tips': 'Dicas de Viajantes',
    'reviews.helpful': 'Útil',
    'reviews.tabMarkets': 'Mercados',
    'reviews.tabVendors': 'Vendedores',
    'reviews.addReviewMarket': 'Avaliar Mercado',
    'reviews.addReviewVendor': 'Avaliar Vendedor',
    'reviews.hideForm': 'Ocultar Formulário',
    'reviews.deleteTitle': 'Excluir Avaliação',
    'reviews.deleteConfirm': 'Tem certeza que deseja excluir esta avaliação? Esta ação não pode ser desfeita.',
    'reviews.delete': 'Excluir',
    'reviews.deleteSuccess': 'Avaliação excluída com sucesso!',
    'reviews.deleteError': 'Erro ao excluir avaliação. Tente novamente.',
    'reviews.noMarketReviews': 'Nenhuma avaliação de mercado ainda.',
    'reviews.noVendorReviews': 'Nenhuma avaliação de vendedor ainda.',
    'reviews.travelerTips': 'Dicas de Viajantes',
    'reviews.userPhotos': 'Fotos de Visitantes',
    
    // Home Page Content
    'home.whyVisit.title': 'Por que visitar os mercados do Recife?',
    'home.whyVisit.text1': 'Os mercados públicos do Recife são muito mais do que lugares para compras. São verdadeiros centros culturais onde você pode vivenciar a alma pernambucana, conhecer pessoas locais, experimentar sabores autênticos e levar para casa memórias e produtos únicos.',
    'home.whyVisit.text2': 'Cada mercado conta uma história diferente e oferece uma experiência única que conecta passado e presente da cidade.',
    'home.experiences.title': 'O que você vai encontrar',
    'home.experience.gastronomy.title': 'Gastronomia Autêntica',
    'home.experience.gastronomy.desc': 'Experimente tapiocas, bolo de rolo, cartola e outros sabores únicos da culinária pernambucana direto da fonte.',
    'home.experience.handicrafts.title': 'Artesanato Local',
    'home.experience.handicrafts.desc': 'Descubra peças únicas feitas por artesãos locais: cerâmica, rendas, esculturas em madeira e muito mais.',
    'home.experience.culture.title': 'Cultura Viva',
    'home.experience.culture.desc': 'Mergulhe na energia vibrante do Recife, com música ao vivo, repentistas e a hospitalidade nordestina.',
    'home.experience.products.title': 'Produtos Frescos',
    'home.experience.products.desc': 'Frutas tropicais, peixes frescos, especiarias exóticas e ingredientes que você não encontra em outro lugar.',
    'home.tips.title': 'Dicas para sua visita',
    'home.tips.tip1': 'Vá cedo pela manhã para ver os mercados em seu momento mais autêntico e movimentado',
    'home.tips.tip2': 'Leve dinheiro em espécie, pois muitos vendedores não aceitam cartão',
    'home.tips.tip3': 'Use roupas leves e calçados confortáveis para caminhar',
    'home.tips.tip4': 'Experimente a tapioca e o caldo de cana fresquinho - são imperdíveis!',
    'home.tips.tip5': 'Converse com os vendedores - eles adoram compartilhar histórias e dicas locais',
    'home.tips.tip6': 'Não esqueça sua câmera - os mercados são muito fotogênicos!',
    'home.cta.title': 'Pronto para a aventura?',
    'home.cta.text': 'Os mercados públicos do Recife te esperam com portas abertas, sabores inesquecíveis e experiências autênticas. Venha fazer parte dessa história!',
    'home.cta.button': 'Planejar minha visita',
    
    // Footer
    'footer.tagline': 'Incentivando o turismo cultural e sustentável no Recife',
    
    // Dynamic content labels
    'dynamic.story': 'História',
    'dynamic.description': 'Descrição',
    'dynamic.comment': 'Comentário',
    'dynamic.rating': 'Avaliação',
    'dynamic.date': 'Data',
    'dynamic.vendor': 'Vendedor',
    'dynamic.market': 'Mercado',
    'dynamic.new': 'Novo',
    'dynamic.products': 'Produtos',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.signup': 'Cadastre-se',
    'auth.logout': 'Sair',
    'auth.profile': 'Perfil',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.name': 'Nome',
    'auth.createAccount': 'Criar Conta',
    'auth.hasAccount': 'Já tem uma conta?',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.loginDescription': 'Entre para compartilhar suas experiências',
    'auth.signupDescription': 'Junte-se à comunidade dos mercados do Recife',
    'auth.loginError': 'Email ou senha incorretos',
    'auth.signupError': 'Este email já está cadastrado',
    'auth.passwordMismatch': 'As senhas não coincidem',
    'auth.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'auth.loading': 'Carregando...',
    
    // Profile
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações e favoritos',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.favorites': 'Favoritos',
    'profile.editProfile': 'Editar Perfil',
    'profile.editDescription': 'Atualize suas informações pessoais',
    'profile.name': 'Nome',
    'profile.namePlaceholder': 'Seu nome completo',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'seu@email.com',
    'profile.changePassword': 'Alterar Senha (opcional)',
    'profile.newPassword': 'Nova Senha',
    'profile.passwordPlaceholder': 'Deixe em branco para manter a senha atual',
    'profile.confirmPassword': 'Confirmar Nova Senha',
    'profile.confirmPasswordPlaceholder': 'Confirme a nova senha',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.updating': 'Atualizando...',
    'profile.updateSuccess': 'Perfil atualizado com sucesso!',
    'profile.updateError': 'Erro ao atualizar perfil. Tente novamente.',
    'profile.passwordMismatch': 'As senhas não coincidem',
    'profile.nameRequired': 'O nome é obrigatório',
    'profile.reloginRequired': 'Email alterado. Faça login novamente.',
    'profile.loginRequired': 'Você precisa estar logado para acessar o perfil',
    'profile.favoriteMarkets': 'Mercados Favoritos',
    'profile.favoriteVendors': 'Vendedores Favoritos',
    'profile.noFavoriteMarkets': 'Nenhum mercado favoritado ainda',
    'profile.noFavoriteVendors': 'Nenhum vendedor favoritado ainda',
    'profile.favoriteMarketsCount': '{count} mercado(s) favorito(s)',
    'profile.favoriteVendorsCount': '{count} vendedor(es) favorito(s)',
    'profile.addedOn': 'Adicionado em',
    'profile.removeFavoriteTitle': 'Remover dos Favoritos',
    'profile.removeFavoriteDescription': 'Tem certeza que deseja remover este item dos favoritos?',
    'profile.favoriteRemoved': 'Removido dos favoritos',
    'profile.removeError': 'Erro ao remover dos favoritos',
    
    // Market Registration
    'marketReg.title': 'Cadastrar Mercado',
    'marketReg.subtitle': 'Compartilhe seu mercado com visitantes',
    'marketReg.formTitle': 'Informações do Mercado',
    'marketReg.formDescription': 'Preencha as informações sobre o mercado',
    'marketReg.nameLabel': 'Nome do Mercado',
    'marketReg.namePlaceholder': 'Ex: Mercado da Guabiraba',
    'marketReg.descriptionLabel': 'Descrição',
    'marketReg.descriptionPlaceholder': 'Descreva o mercado, sua história e características...',
    'marketReg.addressLabel': 'Endereço',
    'marketReg.addressPlaceholder': 'Rua, número, bairro, cidade',
    'marketReg.phoneLabel': 'Telefone',
    'marketReg.phonePlaceholder': '(81) 9999-9999',
    'marketReg.hoursLabel': 'Horário de Funcionamento',
    'marketReg.hoursPlaceholder': 'Ex: Seg-Sáb: 6h-18h',
    'marketReg.photosLabel': 'Fotos do Mercado',
    'marketReg.photoUrlPlaceholder': 'URL da foto',
    'marketReg.createButton': 'Cadastrar Mercado',
    'marketReg.creating': 'Cadastrando...',
    'marketReg.createSuccess': 'Mercado cadastrado com sucesso!',
    'marketReg.createError': 'Erro ao cadastrar mercado. Tente novamente.',
    'marketReg.requiredFields': 'Preencha todos os campos obrigatórios',
    'marketReg.requiredFieldsNote': 'Campos obrigatórios',
    'marketReg.loginRequired': 'Você precisa estar logado para cadastrar um mercado',
    
    // Search
    'search.title': 'Pesquisa: Mercados / Vendedores',
    'search.subtitle': 'Encontre mercados e vendedores do Recife',
    'search.placeholder': 'Buscar por nome, especialidade, endereço...',
    'search.marketsTab': 'Mercados',
    'search.vendorsTab': 'Vendedores',
    'search.noMarketsFound': 'Nenhum mercado encontrado',
    'search.noVendorsFound': 'Nenhum vendedor encontrado',
    'search.verified': 'Verificado',
    'search.pending': 'Pendente',
    'search.by': 'por',
    'search.loginToFavorite': 'Faça login para favoritar',
    'search.addedToFavorites': 'Adicionado aos favoritos',
    'search.removedFromFavorites': 'Removido dos favoritos',
    'search.favoriteError': 'Erro ao gerenciar favoritos',
    'search.loadError': 'Erro ao carregar dados',
    
    // Common additions
    'common.remove': 'Remover',
    'nav.login': 'Entrar',
    'nav.profile': 'Perfil',
    'nav.registerMarket': 'Cadastrar Mercado',
    'nav.search': 'Pesquisar',
    'nav.manageMarkets': 'Meus Mercados',
    
    // Manage Markets
    'manageMarkets.title': 'Meus Mercados',
    'manageMarkets.subtitle': 'Gerencie os mercados que você cadastrou',
    'manageMarkets.loginRequired': 'Você precisa estar logado para gerenciar mercados',
    'manageMarkets.noMarkets': 'Você ainda não cadastrou nenhum mercado',
    'manageMarkets.createFirst': 'Cadastrar Primeiro Mercado',
    'manageMarkets.verified': 'Verificado',
    'manageMarkets.pending': 'Pendente',
    'manageMarkets.photos': 'fotos',
    'manageMarkets.edit': 'Editar',
    'manageMarkets.delete': 'Excluir',
    'manageMarkets.editTitle': 'Editar Mercado',
    'manageMarkets.editDescription': 'Atualize as informações do seu mercado',
    'manageMarkets.nameLabel': 'Nome do Mercado',
    'manageMarkets.namePlaceholder': 'Ex: Mercado da Guabiraba',
    'manageMarkets.descriptionLabel': 'Descrição',
    'manageMarkets.descriptionPlaceholder': 'Descreva o mercado, sua história e características...',
    'manageMarkets.addressLabel': 'Endereço',
    'manageMarkets.addressPlaceholder': 'Rua, número, bairro, cidade',
    'manageMarkets.phoneLabel': 'Telefone',
    'manageMarkets.phonePlaceholder': '(81) 9999-9999',
    'manageMarkets.hoursLabel': 'Horário de Funcionamento',
    'manageMarkets.hoursPlaceholder': 'Ex: Seg-Sáb: 6h-18h',
    'manageMarkets.photosLabel': 'Fotos do Mercado',
    'manageMarkets.save': 'Salvar Alterações',
    'manageMarkets.saving': 'Salvando...',
    'manageMarkets.deleteTitle': 'Excluir Mercado',
    'manageMarkets.deleteConfirm': 'Tem certeza que deseja excluir o mercado "{name}"? Esta ação não pode ser desfeita.',
    'manageMarkets.deleting': 'Excluindo...',
    'manageMarkets.loadError': 'Erro ao carregar mercados',
    'manageMarkets.updateSuccess': 'Mercado atualizado com sucesso!',
    'manageMarkets.updateError': 'Erro ao atualizar mercado',
    'manageMarkets.deleteSuccess': 'Mercado excluído com sucesso!',
    'manageMarkets.deleteError': 'Erro ao excluir mercado',
    'manageMarkets.nameRequired': 'O nome do mercado é obrigatório',
    'manageMarkets.descriptionRequired': 'A descrição é obrigatória',
    'manageMarkets.addressRequired': 'O endereço é obrigatório',
    
    // All Markets Page
    'allMarkets.title': 'Todos os Mercados',
    'allMarkets.subtitle': 'Explore todos os mercados cadastrados no Recife',
    'allMarkets.searchPlaceholder': 'Buscar por nome, descrição ou endereço...',
    'allMarkets.marketsFound': '{count} mercado(s) encontrado(s)',
    'allMarkets.noMarkets': 'Nenhum mercado encontrado',
    'allMarkets.tryDifferentSearch': 'Tente buscar com palavras diferentes',
    'allMarkets.beFirstToAdd': 'Seja o primeiro a cadastrar um mercado!',
    'allMarkets.verified': 'Verificado',
    'allMarkets.pending': 'Pendente',
    'allMarkets.loadError': 'Erro ao carregar mercados. Por favor, tente novamente.',
  },
  en: {
    ...dataTranslationsEN,
    // Navigation
    'nav.home': 'Home',
    'nav.markets': 'Markets',
    'nav.vendors': 'Vendors',
    'nav.itineraries': 'Itineraries',
    'nav.reviews': 'Reviews',
    
    // Hero
    'hero.title': 'Discover Recife\'s Public Markets',
    'hero.subtitle': 'Authentic flavors, unique crafts and the true culture of Pernambuco await you',
    'hero.cta': 'Explore Markets',
    
    // Common
    'common.location': 'Location',
    'common.hours': 'Hours',
    'common.highlights': 'Highlights',
    'common.viewDetails': 'View Details',
    'common.search': 'Search',
    'common.searchVendors': 'Search by name, specialty or market',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.reviews': 'Reviews',
    'common.photos': 'Photos',
    'common.cancel': 'Cancel',
    
    // Markets
    'markets.title': 'Main Markets',
    'markets.subtitle': 'Discover the most traditional and vibrant markets in Recife',
    'markets.saoJose.name': 'Mercado de São José',
    'markets.saoJose.desc': 'The oldest continuously operating public market in Brazil, founded in 1875.',
    'markets.boaVista.name': 'Mercado da Boa Vista',
    'markets.boaVista.desc': 'Known for its variety of fresh products and authenticity.',
    'markets.casaAmarela.name': 'Mercado de Casa Amarela',
    'markets.casaAmarela.desc': 'A vibrant and welcoming market where you can find everything from food to handicrafts.',
    
    // Market Details
    'market.about': 'About the Market',
    'market.history': 'History',
    'market.products': 'Products',
    'market.howToGet': 'How to Get There',
    'market.gallery': 'Gallery',
    'market.featuredVendors': 'Featured Vendors',
    
    // Vendors
    'vendors.title': 'Meet the Vendors',
    'vendors.subtitle': 'The people who make the magic happen in the markets',
    'vendors.filterByProduct': 'Filter by Product',
    'vendors.location': 'Stall location',
    'vendors.specialty': 'Specialty',
    'vendors.tabList': 'Vendors',
    'vendors.tabRegister': 'Register as Vendor',
    'vendors.registerTitle': 'Register as a Vendor',
    'vendors.registerSubtitle': 'Share your story and products with visitors',
    'vendors.formName': 'Name',
    'vendors.formNamePlaceholder': 'Your name or stall name',
    'vendors.formDescription': 'Description / Story',
    'vendors.formDescriptionPlaceholder': 'Tell your story, how you started, family traditions...',
    'vendors.formSpecialty': 'Specialty',
    'vendors.formSpecialtyPlaceholder': 'E.g: Medicinal herbs and natural teas',
    'vendors.formMarket': 'Market where you work',
    'vendors.formMarketPlaceholder': 'Select the market',
    'vendors.formProducts': 'Products you sell',
    'vendors.formLocation': 'Stall Location',
    'vendors.formLocationPlaceholder': 'E.g: Stall 12, Aisle A',
    'vendors.productErvas': 'Herbs',
    'vendors.productEspeciarias': 'Spices',
    'vendors.productArtesanato': 'Handicrafts',
    'vendors.productComida': 'Food',
    'vendors.productFrutas': 'Fruits',
    'vendors.productCeramica': 'Ceramics',
    'vendors.productChas': 'Teas',
    'vendors.productTapioca': 'Tapioca',
    'vendors.formBadges': 'Authenticity Seals',
    'vendors.formBadgesDescription': 'Highlight your special characteristics',
    'vendors.badgeHandmade': '🎨 Handmade',
    'vendors.badgeLocal': '📍 Local Production',
    'vendors.badgeFamily': '👨‍👩‍👧‍👦 Family Recipe',
    'vendors.submitButton': 'Register',
    'vendors.submitting': 'Registering...',
    'vendors.updateButton': 'Update',
    'vendors.updating': 'Updating...',
    'vendors.successMessage': 'Successfully registered!',
    'vendors.errorMessage': 'Error registering. Please try again.',
    'vendors.loginRequired': 'You must be logged in to register as a vendor',
    'vendors.editProfile': 'Edit Profile',
    'vendors.deleteProfile': 'Delete Profile',
    'vendors.deleteConfirm': 'Are you sure you want to delete your profile? This action cannot be undone.',
    'vendors.deleteSuccess': 'Profile deleted successfully!',
    'vendors.deleteError': 'Error deleting profile. Please try again.',
    'vendors.tabEdit': 'Edit Profile',
    'vendors.noVendors': 'No vendors registered yet.',
    
    // Itineraries
    'itineraries.title': 'Suggested Itineraries',
    'itineraries.subtitle': 'Plan your visit with our themed guides',
    'itineraries.duration': 'Duration',
    'itineraries.stops': 'Stops',
    'itineraries.checklist': 'Experience Checklist',
    
    // Reviews
    'reviews.title': 'What Visitors Say',
    'reviews.subtitle': 'Real experiences from those who have visited',
    'reviews.leaveReview': 'Leave a Review',
    'reviews.userGallery': 'Visitor Gallery',
    'reviews.tips': 'Traveler Tips',
    'reviews.helpful': 'Helpful',
    'reviews.tabMarkets': 'Markets',
    'reviews.tabVendors': 'Vendors',
    'reviews.addReviewMarket': 'Review Market',
    'reviews.addReviewVendor': 'Review Vendor',
    'reviews.hideForm': 'Hide Form',
    'reviews.deleteTitle': 'Delete Review',
    'reviews.deleteConfirm': 'Are you sure you want to delete this review? This action cannot be undone.',
    'reviews.delete': 'Delete',
    'reviews.deleteSuccess': 'Review deleted successfully!',
    'reviews.deleteError': 'Error deleting review. Please try again.',
    'reviews.noMarketReviews': 'No market reviews yet.',
    'reviews.noVendorReviews': 'No vendor reviews yet.',
    'reviews.travelerTips': 'Traveler Tips',
    'reviews.userPhotos': 'Visitor Photos',
    
    // Home Page Content
    'home.whyVisit.title': 'Why visit Recife\'s markets?',
    'home.whyVisit.text1': 'Recife\'s public markets are much more than shopping places. They are true cultural centers where you can experience the Pernambuco soul, meet locals, try authentic flavors, and take home unique memories and products.',
    'home.whyVisit.text2': 'Each market tells a different story and offers a unique experience that connects the city\'s past and present.',
    'home.experiences.title': 'What you will find',
    'home.experience.gastronomy.title': 'Authentic Gastronomy',
    'home.experience.gastronomy.desc': 'Try tapiocas, bolo de rolo, cartola and other unique flavors of Pernambuco cuisine straight from the source.',
    'home.experience.handicrafts.title': 'Local Handicrafts',
    'home.experience.handicrafts.desc': 'Discover unique pieces made by local artisans: ceramics, laces, wood sculptures and much more.',
    'home.experience.culture.title': 'Living Culture',
    'home.experience.culture.desc': 'Immerse yourself in Recife\'s vibrant energy, with live music, repentistas and northeastern hospitality.',
    'home.experience.products.title': 'Fresh Products',
    'home.experience.products.desc': 'Tropical fruits, fresh fish, exotic spices and ingredients you won\'t find anywhere else.',
    'home.tips.title': 'Tips for your visit',
    'home.tips.tip1': 'Go early in the morning to see the markets at their most authentic and busy',
    'home.tips.tip2': 'Bring cash, as many vendors don\'t accept cards',
    'home.tips.tip3': 'Wear light clothing and comfortable shoes for walking',
    'home.tips.tip4': 'Try the tapioca and fresh sugarcane juice - they\'re unmissable!',
    'home.tips.tip5': 'Talk to the vendors - they love sharing stories and local tips',
    'home.tips.tip6': 'Don\'t forget your camera - the markets are very photogenic!',
    'home.cta.title': 'Ready for the adventure?',
    'home.cta.text': 'Recife\'s public markets await you with open doors, unforgettable flavors and authentic experiences. Come be part of this story!',
    'home.cta.button': 'Plan my visit',
    
    // Footer
    'footer.tagline': 'Promoting cultural and sustainable tourism in Recife',
    
    // Dynamic content labels
    'dynamic.story': 'Story',
    'dynamic.description': 'Description',
    'dynamic.comment': 'Comment',
    'dynamic.rating': 'Rating',
    'dynamic.date': 'Date',
    'dynamic.vendor': 'Vendor',
    'dynamic.market': 'Market',
    'dynamic.new': 'New',
    'dynamic.products': 'Products',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.profile': 'Profile',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.createAccount': 'Create Account',
    'auth.hasAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.loginDescription': 'Login to share your experiences',
    'auth.signupDescription': 'Join the Recife markets community',
    'auth.loginError': 'Incorrect email or password',
    'auth.signupError': 'This email is already registered',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.loading': 'Loading...',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your information and favorites',
    'profile.personalInfo': 'Personal Information',
    'profile.favorites': 'Favorites',
    'profile.editProfile': 'Edit Profile',
    'profile.editDescription': 'Update your personal information',
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Your full name',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'your@email.com',
    'profile.changePassword': 'Change Password (optional)',
    'profile.newPassword': 'New Password',
    'profile.passwordPlaceholder': 'Leave blank to keep current password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.confirmPasswordPlaceholder': 'Confirm new password',
    'profile.saveChanges': 'Save Changes',
    'profile.updating': 'Updating...',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.updateError': 'Error updating profile. Please try again.',
    'profile.passwordMismatch': 'Passwords do not match',
    'profile.nameRequired': 'Name is required',
    'profile.reloginRequired': 'Email changed. Please login again.',
    'profile.loginRequired': 'You must be logged in to access profile',
    'profile.favoriteMarkets': 'Favorite Markets',
    'profile.favoriteVendors': 'Favorite Vendors',
    'profile.noFavoriteMarkets': 'No favorite markets yet',
    'profile.noFavoriteVendors': 'No favorite vendors yet',
    'profile.favoriteMarketsCount': '{count} favorite market(s)',
    'profile.favoriteVendorsCount': '{count} favorite vendor(s)',
    'profile.addedOn': 'Added on',
    'profile.removeFavoriteTitle': 'Remove from Favorites',
    'profile.removeFavoriteDescription': 'Are you sure you want to remove this item from favorites?',
    'profile.favoriteRemoved': 'Removed from favorites',
    'profile.removeError': 'Error removing from favorites',
    
    // Market Registration
    'marketReg.title': 'Register Market',
    'marketReg.subtitle': 'Share your market with visitors',
    'marketReg.formTitle': 'Market Information',
    'marketReg.formDescription': 'Fill in the market details',
    'marketReg.nameLabel': 'Market Name',
    'marketReg.namePlaceholder': 'E.g: Mercado da Guabiraba',
    'marketReg.descriptionLabel': 'Description',
    'marketReg.descriptionPlaceholder': 'Describe the market, its history and features...',
    'marketReg.addressLabel': 'Address',
    'marketReg.addressPlaceholder': 'Street, number, neighborhood, city',
    'marketReg.phoneLabel': 'Phone',
    'marketReg.phonePlaceholder': '(81) 9999-9999',
    'marketReg.hoursLabel': 'Opening Hours',
    'marketReg.hoursPlaceholder': 'E.g: Mon-Sat: 6am-6pm',
    'marketReg.photosLabel': 'Market Photos',
    'marketReg.photoUrlPlaceholder': 'Photo URL',
    'marketReg.createButton': 'Register Market',
    'marketReg.creating': 'Registering...',
    'marketReg.createSuccess': 'Market registered successfully!',
    'marketReg.createError': 'Error registering market. Please try again.',
    'marketReg.requiredFields': 'Please fill all required fields',
    'marketReg.requiredFieldsNote': 'Required fields',
    'marketReg.loginRequired': 'You must be logged in to register a market',
    
    // Search
    'search.title': 'Search: Markets / Vendors',
    'search.subtitle': 'Find markets and vendors in Recife',
    'search.placeholder': 'Search by name, specialty, address...',
    'search.marketsTab': 'Markets',
    'search.vendorsTab': 'Vendors',
    'search.noMarketsFound': 'No markets found',
    'search.noVendorsFound': 'No vendors found',
    'search.verified': 'Verified',
    'search.pending': 'Pending',
    'search.by': 'by',
    'search.loginToFavorite': 'Login to favorite',
    'search.addedToFavorites': 'Added to favorites',
    'search.removedFromFavorites': 'Removed from favorites',
    'search.favoriteError': 'Error managing favorites',
    'search.loadError': 'Error loading data',
    
    // Common additions
    'common.remove': 'Remove',
    'nav.login': 'Login',
    'nav.profile': 'Profile',
    'nav.registerMarket': 'Register Market',
    'nav.search': 'Search',
    'nav.manageMarkets': 'My Markets',
    
    // Manage Markets
    'manageMarkets.title': 'My Markets',
    'manageMarkets.subtitle': 'Manage the markets you registered',
    'manageMarkets.loginRequired': 'You must be logged in to manage markets',
    'manageMarkets.noMarkets': 'You haven\'t registered any markets yet',
    'manageMarkets.createFirst': 'Register First Market',
    'manageMarkets.verified': 'Verified',
    'manageMarkets.pending': 'Pending',
    'manageMarkets.photos': 'photos',
    'manageMarkets.edit': 'Edit',
    'manageMarkets.delete': 'Delete',
    'manageMarkets.editTitle': 'Edit Market',
    'manageMarkets.editDescription': 'Update your market information',
    'manageMarkets.nameLabel': 'Market Name',
    'manageMarkets.namePlaceholder': 'E.g: Mercado da Guabiraba',
    'manageMarkets.descriptionLabel': 'Description',
    'manageMarkets.descriptionPlaceholder': 'Describe the market, its history and features...',
    'manageMarkets.addressLabel': 'Address',
    'manageMarkets.addressPlaceholder': 'Street, number, neighborhood, city',
    'manageMarkets.phoneLabel': 'Phone',
    'manageMarkets.phonePlaceholder': '(81) 9999-9999',
    'manageMarkets.hoursLabel': 'Opening Hours',
    'manageMarkets.hoursPlaceholder': 'E.g: Mon-Sat: 6am-6pm',
    'manageMarkets.photosLabel': 'Market Photos',
    'manageMarkets.save': 'Save Changes',
    'manageMarkets.saving': 'Saving...',
    'manageMarkets.deleteTitle': 'Delete Market',
    'manageMarkets.deleteConfirm': 'Are you sure you want to delete the market "{name}"? This action cannot be undone.',
    'manageMarkets.deleting': 'Deleting...',
    'manageMarkets.loadError': 'Error loading markets',
    'manageMarkets.updateSuccess': 'Market updated successfully!',
    'manageMarkets.updateError': 'Error updating market',
    'manageMarkets.deleteSuccess': 'Market deleted successfully!',
    'manageMarkets.deleteError': 'Error deleting market',
    'manageMarkets.nameRequired': 'Market name is required',
    'manageMarkets.descriptionRequired': 'Description is required',
    'manageMarkets.addressRequired': 'Address is required',
    
    // All Markets Page
    'allMarkets.title': 'All Markets',
    'allMarkets.subtitle': 'Explore all registered markets in Recife',
    'allMarkets.searchPlaceholder': 'Search by name, description or address...',
    'allMarkets.marketsFound': '{count} market(s) found',
    'allMarkets.noMarkets': 'No markets found',
    'allMarkets.tryDifferentSearch': 'Try searching with different keywords',
    'allMarkets.beFirstToAdd': 'Be the first to register a market!',
    'allMarkets.verified': 'Verified',
    'allMarkets.pending': 'Pending',
    'allMarkets.loadError': 'Error loading markets. Please try again.',
  },
  es: {
    ...dataTranslationsES,
    // Navigation
    'nav.home': 'Inicio',
    'nav.markets': 'Mercados',
    'nav.vendors': 'Vendedores',
    'nav.itineraries': 'Itinerarios',
    'nav.reviews': 'Reseñas',
    
    // Hero
    'hero.title': 'Descubre los Mercados Públicos de Recife',
    'hero.subtitle': 'Sabores auténticos, artesanía única y la verdadera cultura de Pernambuco te esperan',
    'hero.cta': 'Explorar Mercados',
    
    // Common
    'common.location': 'Ubicación',
    'common.hours': 'Horario',
    'common.highlights': 'Destacados',
    'common.viewDetails': 'Ver Detalles',
    'common.search': 'Buscar',
    'common.searchVendors': 'Buscar por nombre, especialidad o mercado',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.reviews': 'Reseñas',
    'common.photos': 'Fotos',
    'common.cancel': 'Cancelar',
    
    // Markets
    'markets.title': 'Principales Mercados',
    'markets.subtitle': 'Conoce los mercados más tradicionales y vibrantes de Recife',
    'markets.saoJose.name': 'Mercado de São José',
    'markets.saoJose.desc': 'El mercado público en funcionamiento continuo más antiguo de Brasil, fundado en 1875.',
    'markets.boaVista.name': 'Mercado de Boa Vista',
    'markets.boaVista.desc': 'Conocido por su variedad de productos frescos y autenticidad.',
    'markets.casaAmarela.name': 'Mercado de Casa Amarela',
    'markets.casaAmarela.desc': 'Un mercado vibrante y acogedor donde encontrarás desde alimentos hasta artesanía.',
    
    // Market Details
    'market.about': 'Sobre el Mercado',
    'market.history': 'Historia',
    'market.products': 'Productos',
    'market.howToGet': 'Cómo Llegar',
    'market.gallery': 'Galería',
    'market.featuredVendors': 'Vendedores Destacados',
    
    // Vendors
    'vendors.title': 'Conoce a los Vendedores',
    'vendors.subtitle': 'Las personas que hacen la magia en los mercados',
    'vendors.filterByProduct': 'Filtrar por Producto',
    'vendors.location': 'Ubicación del puesto',
    'vendors.specialty': 'Especialidad',
    'vendors.tabList': 'Vendedores',
    'vendors.tabRegister': 'Regístrate como Vendedor',
    'vendors.registerTitle': 'Regístrate como Vendedor',
    'vendors.registerSubtitle': 'Comparte tu historia y productos con los visitantes',
    'vendors.formName': 'Nombre',
    'vendors.formNamePlaceholder': 'Tu nombre o nombre del puesto',
    'vendors.formDescription': 'Descripción / Historia',
    'vendors.formDescriptionPlaceholder': 'Cuenta tu historia, cómo empezaste, tradiciones familiares...',
    'vendors.formSpecialty': 'Especialidad',
    'vendors.formSpecialtyPlaceholder': 'Ej: Hierbas medicinales y tés naturales',
    'vendors.formMarket': 'Mercado donde trabajas',
    'vendors.formMarketPlaceholder': 'Selecciona el mercado',
    'vendors.formProducts': 'Productos que vendes',
    'vendors.formLocation': 'Ubicación del Puesto',
    'vendors.formLocationPlaceholder': 'Ej: Puesto 12, Pasillo A',
    'vendors.productErvas': 'Hierbas',
    'vendors.productEspeciarias': 'Especias',
    'vendors.productArtesanato': 'Artesanía',
    'vendors.productComida': 'Comida',
    'vendors.productFrutas': 'Frutas',
    'vendors.productCeramica': 'Cerámica',
    'vendors.productChas': 'Tés',
    'vendors.productTapioca': 'Tapioca',
    'vendors.formBadges': 'Sellos de Autenticidad',
    'vendors.formBadgesDescription': 'Destaca tus características especiales',
    'vendors.badgeHandmade': '🎨 Hecho a Mano',
    'vendors.badgeLocal': '📍 Producción Local',
    'vendors.badgeFamily': '👨‍👩‍👧‍👦 Receta de Familia',
    'vendors.submitButton': 'Registrar',
    'vendors.submitting': 'Registrando...',
    'vendors.updateButton': 'Actualizar',
    'vendors.updating': 'Actualizando...',
    'vendors.successMessage': '¡Registro exitoso!',
    'vendors.errorMessage': 'Error al registrar. Intenta nuevamente.',
    'vendors.loginRequired': 'Debes iniciar sesión para registrarte como vendedor',
    'vendors.editProfile': 'Editar Perfil',
    'vendors.deleteProfile': 'Eliminar Perfil',
    'vendors.deleteConfirm': '¿Estás seguro de que quieres eliminar tu perfil? Esta acción no se puede deshacer.',
    'vendors.deleteSuccess': '¡Perfil eliminado con éxito!',
    'vendors.deleteError': 'Error al eliminar perfil. Intenta nuevamente.',
    'vendors.tabEdit': 'Editar Perfil',
    'vendors.noVendors': 'Aún no hay vendedores registrados.',
    
    // Itineraries
    'itineraries.title': 'Itinerarios Sugeridos',
    'itineraries.subtitle': 'Planifica tu visita con nuestras guías temáticas',
    'itineraries.duration': 'Duración',
    'itineraries.stops': 'Paradas',
    'itineraries.checklist': 'Lista de Experiencias',
    
    // Reviews
    'reviews.title': 'Lo Que Dicen los Visitantes',
    'reviews.subtitle': 'Experiencias reales de quienes ya visitaron',
    'reviews.leaveReview': 'Dejar Reseña',
    'reviews.userGallery': 'Galería de Visitantes',
    'reviews.tips': 'Consejos de Viajeros',
    'reviews.helpful': 'Útil',
    'reviews.tabMarkets': 'Mercados',
    'reviews.tabVendors': 'Vendedores',
    'reviews.addReviewMarket': 'Reseñar Mercado',
    'reviews.addReviewVendor': 'Reseñar Vendedor',
    'reviews.hideForm': 'Ocultar Formulario',
    'reviews.deleteTitle': 'Eliminar Reseña',
    'reviews.deleteConfirm': '¿Estás seguro de que quieres eliminar esta reseña? Esta acción no se puede deshacer.',
    'reviews.delete': 'Eliminar',
    'reviews.deleteSuccess': '¡Reseña eliminada con éxito!',
    'reviews.deleteError': 'Error al eliminar reseña. Intenta nuevamente.',
    'reviews.noMarketReviews': 'Aún no hay reseñas de mercados.',
    'reviews.noVendorReviews': 'Aún no hay reseñas de vendedores.',
    'reviews.travelerTips': 'Consejos de Viajeros',
    'reviews.userPhotos': 'Fotos de Visitantes',
    
    // Home Page Content
    'home.whyVisit.title': '¿Por qué visitar los mercados de Recife?',
    'home.whyVisit.text1': 'Los mercados públicos de Recife son mucho más que lugares de compras. Son verdaderos centros culturales donde puedes vivir el alma de Pernambuco, conocer a la gente local, probar sabores auténticos y llevarte a casa recuerdos y productos únicos.',
    'home.whyVisit.text2': 'Cada mercado cuenta una historia diferente y ofrece una experiencia única que conecta el pasado y presente de la ciudad.',
    'home.experiences.title': 'Lo que encontrarás',
    'home.experience.gastronomy.title': 'Gastronomía Auténtica',
    'home.experience.gastronomy.desc': 'Prueba tapiocas, bolo de rolo, cartola y otros sabores únicos de la cocina de Pernambuco directamente de la fuente.',
    'home.experience.handicrafts.title': 'Artesanía Local',
    'home.experience.handicrafts.desc': 'Descubre piezas únicas hechas por artesanos locales: cerámica, encajes, esculturas de madera y mucho más.',
    'home.experience.culture.title': 'Cultura Viva',
    'home.experience.culture.desc': 'Sumérgete en la energía vibrante de Recife, con música en vivo, repentistas y la hospitalidad del nordeste.',
    'home.experience.products.title': 'Productos Frescos',
    'home.experience.products.desc': 'Frutas tropicales, pescado fresco, especias exóticas e ingredientes que no encontrarás en otro lugar.',
    'home.tips.title': 'Consejos para tu visita',
    'home.tips.tip1': 'Ve temprano por la mañana para ver los mercados en su momento más auténtico y concurrido',
    'home.tips.tip2': 'Lleva efectivo, ya que muchos vendedores no aceptan tarjetas',
    'home.tips.tip3': 'Usa ropa ligera y calzado cómodo para caminar',
    'home.tips.tip4': '¡Prueba la tapioca y el jugo de caña fresco - son imperdibles!',
    'home.tips.tip5': 'Habla con los vendedores - les encanta compartir historias y consejos locales',
    'home.tips.tip6': '¡No olvides tu cámara - los mercados son muy fotogénicos!',
    'home.cta.title': '¿Listo para la aventura?',
    'home.cta.text': 'Los mercados públicos de Recife te esperan con las puertas abiertas, sabores inolvidables y experiencias auténticas. ¡Ven a ser parte de esta historia!',
    'home.cta.button': 'Planificar mi visita',
    
    // Footer
    'footer.tagline': 'Promoviendo el turismo cultural y sostenible en Recife',
    
    // Dynamic content labels
    'dynamic.story': 'Historia',
    'dynamic.description': 'Descripción',
    'dynamic.comment': 'Comentario',
    'dynamic.rating': 'Calificación',
    'dynamic.date': 'Fecha',
    'dynamic.vendor': 'Vendedor',
    'dynamic.market': 'Mercado',
    'dynamic.new': 'Nuevo',
    'dynamic.products': 'Productos',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.logout': 'Cerrar Sesión',
    'auth.profile': 'Perfil',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.name': 'Nombre',
    'auth.createAccount': 'Crear Cuenta',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.loginDescription': 'Inicia sesión para compartir tus experiencias',
    'auth.signupDescription': 'Únete a la comunidad de los mercados de Recife',
    'auth.loginError': 'Email o contraseña incorrectos',
    'auth.signupError': 'Este email ya está registrado',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'auth.loading': 'Cargando...',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Gestiona tu información y favoritos',
    'profile.personalInfo': 'Información Personal',
    'profile.favorites': 'Favoritos',
    'profile.editProfile': 'Editar Perfil',
    'profile.editDescription': 'Actualiza tu información personal',
    'profile.name': 'Nombre',
    'profile.namePlaceholder': 'Tu nombre completo',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'tu@email.com',
    'profile.changePassword': 'Cambiar Contraseña (opcional)',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.passwordPlaceholder': 'Dejar en blanco para mantener contraseña actual',
    'profile.confirmPassword': 'Confirmar Nueva Contraseña',
    'profile.confirmPasswordPlaceholder': 'Confirmar nueva contraseña',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.updating': 'Actualizando...',
    'profile.updateSuccess': '¡Perfil actualizado con éxito!',
    'profile.updateError': 'Error al actualizar perfil. Inténtalo de nuevo.',
    'profile.passwordMismatch': 'Las contraseñas no coinciden',
    'profile.nameRequired': 'El nombre es obligatorio',
    'profile.reloginRequired': 'Email modificado. Inicia sesión nuevamente.',
    'profile.loginRequired': 'Debes iniciar sesión para acceder al perfil',
    'profile.favoriteMarkets': 'Mercados Favoritos',
    'profile.favoriteVendors': 'Vendedores Favoritos',
    'profile.noFavoriteMarkets': 'Ningún mercado favorito aún',
    'profile.noFavoriteVendors': 'Ningún vendedor favorito aún',
    'profile.favoriteMarketsCount': '{count} mercado(s) favorito(s)',
    'profile.favoriteVendorsCount': '{count} vendedor(es) favorito(s)',
    'profile.addedOn': 'Añadido el',
    'profile.removeFavoriteTitle': 'Eliminar de Favoritos',
    'profile.removeFavoriteDescription': '¿Estás seguro de que deseas eliminar este elemento de favoritos?',
    'profile.favoriteRemoved': 'Eliminado de favoritos',
    'profile.removeError': 'Error al eliminar de favoritos',
    
    // Market Registration
    'marketReg.title': 'Registrar Mercado',
    'marketReg.subtitle': 'Comparte tu mercado con visitantes',
    'marketReg.formTitle': 'Información del Mercado',
    'marketReg.formDescription': 'Completa los detalles del mercado',
    'marketReg.nameLabel': 'Nombre del Mercado',
    'marketReg.namePlaceholder': 'Ej: Mercado da Guabiraba',
    'marketReg.descriptionLabel': 'Descripción',
    'marketReg.descriptionPlaceholder': 'Describe el mercado, su historia y características...',
    'marketReg.addressLabel': 'Dirección',
    'marketReg.addressPlaceholder': 'Calle, número, barrio, ciudad',
    'marketReg.phoneLabel': 'Teléfono',
    'marketReg.phonePlaceholder': '(81) 9999-9999',
    'marketReg.hoursLabel': 'Horario de Apertura',
    'marketReg.hoursPlaceholder': 'Ej: Lun-Sáb: 6h-18h',
    'marketReg.photosLabel': 'Fotos del Mercado',
    'marketReg.photoUrlPlaceholder': 'URL de la foto',
    'marketReg.createButton': 'Registrar Mercado',
    'marketReg.creating': 'Registrando...',
    'marketReg.createSuccess': '¡Mercado registrado con éxito!',
    'marketReg.createError': 'Error al registrar mercado. Inténtalo de nuevo.',
    'marketReg.requiredFields': 'Completa todos los campos obligatorios',
    'marketReg.requiredFieldsNote': 'Campos obligatorios',
    'marketReg.loginRequired': 'Debes iniciar sesión para registrar un mercado',
    
    // Search
    'search.title': 'Búsqueda: Mercados / Vendedores',
    'search.subtitle': 'Encuentra mercados y vendedores en Recife',
    'search.placeholder': 'Buscar por nombre, especialidad, dirección...',
    'search.marketsTab': 'Mercados',
    'search.vendorsTab': 'Vendedores',
    'search.noMarketsFound': 'No se encontraron mercados',
    'search.noVendorsFound': 'No se encontraron vendedores',
    'search.verified': 'Verificado',
    'search.pending': 'Pendiente',
    'search.by': 'por',
    'search.loginToFavorite': 'Inicia sesión para favoritar',
    'search.addedToFavorites': 'Añadido a favoritos',
    'search.removedFromFavorites': 'Eliminado de favoritos',
    'search.favoriteError': 'Error al gestionar favoritos',
    'search.loadError': 'Error al cargar datos',
    
    // Common additions
    'common.remove': 'Eliminar',
    'nav.login': 'Iniciar Sesión',
    'nav.profile': 'Perfil',
    'nav.registerMarket': 'Registrar Mercado',
    'nav.search': 'Buscar',
    'nav.manageMarkets': 'Mis Mercados',
    
    // Manage Markets
    'manageMarkets.title': 'Mis Mercados',
    'manageMarkets.subtitle': 'Administra los mercados que registraste',
    'manageMarkets.loginRequired': 'Debes iniciar sesión para administrar mercados',
    'manageMarkets.noMarkets': 'Aún no has registrado ningún mercado',
    'manageMarkets.createFirst': 'Registrar Primer Mercado',
    'manageMarkets.verified': 'Verificado',
    'manageMarkets.pending': 'Pendiente',
    'manageMarkets.photos': 'fotos',
    'manageMarkets.edit': 'Editar',
    'manageMarkets.delete': 'Eliminar',
    'manageMarkets.editTitle': 'Editar Mercado',
    'manageMarkets.editDescription': 'Actualiza la información de tu mercado',
    'manageMarkets.nameLabel': 'Nombre del Mercado',
    'manageMarkets.namePlaceholder': 'Ej: Mercado da Guabiraba',
    'manageMarkets.descriptionLabel': 'Descripción',
    'manageMarkets.descriptionPlaceholder': 'Describe el mercado, su historia y características...',
    'manageMarkets.addressLabel': 'Dirección',
    'manageMarkets.addressPlaceholder': 'Calle, número, barrio, ciudad',
    'manageMarkets.phoneLabel': 'Teléfono',
    'manageMarkets.phonePlaceholder': '(81) 9999-9999',
    'manageMarkets.hoursLabel': 'Horario de Apertura',
    'manageMarkets.hoursPlaceholder': 'Ej: Lun-Sáb: 6am-6pm',
    'manageMarkets.photosLabel': 'Fotos del Mercado',
    'manageMarkets.save': 'Guardar Cambios',
    'manageMarkets.saving': 'Guardando...',
    'manageMarkets.deleteTitle': 'Eliminar Mercado',
    'manageMarkets.deleteConfirm': '¿Estás seguro de que quieres eliminar el mercado "{name}"? Esta acción no se puede deshacer.',
    'manageMarkets.deleting': 'Eliminando...',
    'manageMarkets.loadError': 'Error al cargar mercados',
    'manageMarkets.updateSuccess': '¡Mercado actualizado con éxito!',
    'manageMarkets.updateError': 'Error al actualizar mercado',
    'manageMarkets.deleteSuccess': '¡Mercado eliminado con éxito!',
    'manageMarkets.deleteError': 'Error al eliminar mercado',
    'manageMarkets.nameRequired': 'El nombre del mercado es obligatorio',
    'manageMarkets.descriptionRequired': 'La descripción es obligatoria',
    'manageMarkets.addressRequired': 'La dirección es obligatoria',
    
    // All Markets Page
    'allMarkets.title': 'Todos los Mercados',
    'allMarkets.subtitle': 'Explora todos los mercados registrados en Recife',
    'allMarkets.searchPlaceholder': 'Buscar por nombre, descripción o dirección...',
    'allMarkets.marketsFound': '{count} mercado(s) encontrado(s)',
    'allMarkets.noMarkets': 'No se encontraron mercados',
    'allMarkets.tryDifferentSearch': 'Intenta buscar con palabras diferentes',
    'allMarkets.beFirstToAdd': '¡Sé el primero en registrar un mercado!',
    'allMarkets.verified': 'Verificado',
    'allMarkets.pending': 'Pendiente',
    'allMarkets.loadError': 'Error al cargar mercados. Por favor, intenta de nuevo.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
