

export const projectId = "ckwavnkxqicrhktqmblw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrd2F2bmt4cWljcmhrdHFtYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwODk3NzAsImV4cCI6MjA3NTY2NTc3MH0.DVtcc50hwgaICaadH6hjTqlgYdwbniWeGjmhtSc8VsM"